<meta http-equiv="content-type" content="text/html; charset=utf-8">
<title><?= \analib\Core\Application\Application::me()->getController()->getActionTitle() ?> - <?= strip_tags(\analib\Core\Application\Application::me()->get('sys_name')) ?></title>
<link rel="stylesheet" type="text/css" href="<?= \analib\Core\Application\Application::makeLink('css/style.css') ?>">
<link rel="stylesheet" type="text/css" href="<?= \analib\Core\Application\Application::makeLink('css/menu.css') ?>">
