<?php

if (!defined('ANALIB_DIR_LIB')) {
    define('ANALIB_DIR_LIB', dirname(realpath(__FILE__)));
}

if (!defined('ANALIB_DIR_CLASS_NAME')) {
    define('ANALIB_DIR_CLASS_NAME', 'Classes');
}
if (!defined('ANALIB_DIR_CONTROLLER_NAME')) {
    define('ANALIB_DIR_CONTROLLER_NAME', 'Controller');
}
if (!defined('ANALIB_DIR_CORE_NAME')) {
    define('ANALIB_DIR_CORE_NAME', 'Core');
}
if (!defined('ANALIB_DIR_APPLICATION_NAME')) {
    define('ANALIB_DIR_APPLICATION_NAME', 'Application');
}
if (!defined('ANALIB_DIR_BUILD_NAME')) {
    define('ANALIB_DIR_BUILD_NAME', 'Build');
}
if (!defined('ANALIB_DIR_JPEG_NAME')) {
    define('ANALIB_DIR_JPEG_NAME', 'Jpeg');
}
if (!defined('ANALIB_DIR_DB_NAME')) {
    define('ANALIB_DIR_DB_NAME', 'DB');
}
if (!defined('ANALIB_DIR_MYSQL_NAME')) {
    define('ANALIB_DIR_MYSQL_NAME', 'MySQL');
}
if (!defined('ANALIB_DIR_FILTERS_NAME')) {
    define('ANALIB_DIR_FILTERS_NAME', 'Filters');
}
if (!defined('ANALIB_DIR_FORM_NAME')) {
    define('ANALIB_DIR_FORM_NAME', 'Form');
}
if (!defined('ANALIB_DIR_EXCEPTION_NAME')) {
    define('ANALIB_DIR_EXCEPTION_NAME', 'Exceptions');
}
if (!defined('ANALIB_DIR_HELPER_NAME')) {
    define('ANALIB_DIR_HELPER_NAME', 'Helpers');
}
if (!defined('ANALIB_DIR_HELPER_TEMPLATE_NAME')) {
    define('ANALIB_DIR_HELPER_TEMPLATE_NAME', 'view');
}
if (!defined('ANALIB_DIR_MODEL_NAME')) {
    define('ANALIB_DIR_MODEL_NAME', 'model');
}
if (!defined('ANALIB_DIR_BUSINESS_NAME')) {
    define('ANALIB_DIR_BUSINESS_NAME', 'Business');
}
if (!defined('ANALIB_DIR_PROTO_NAME')) {
    define('ANALIB_DIR_PROTO_NAME', 'Proto');
}
if (!defined('ANALIB_DIR_UTIL_NAME')) {
    define('ANALIB_DIR_UTIL_NAME', 'Util');
}
if (!defined('ANALIB_DIR_TEMPLATE_NAME')) {
    define('ANALIB_DIR_TEMPLATE_NAME', 'templates');
}
if (!defined('ANALIB_DIR_VIEW_NAME')) {
    define('ANALIB_DIR_VIEW_NAME', 'view');
}
if (!defined('ANALIB_DIR_CORE_XML_NAME')) {
    define('ANALIB_DIR_CORE_XML_NAME', 'Xml');
}
if (!defined('ANALIB_DIR_FB2_NAME')) {
    define('ANALIB_DIR_FB2_NAME', 'Fb2');
}
if (!defined('ANALIB_DIR_DB_NAME')) {
    define('ANALIB_DIR_DB_NAME', 'DB');
}
if (!defined('ANALIB_DIR_XML')) {
    define('ANALIB_DIR_XML', 'xml');
}

define('ANALIB_DIR_LIB_CONTROLLER', ANALIB_DIR_LIB . DIRECTORY_SEPARATOR . ANALIB_DIR_CONTROLLER_NAME);
define('ANALIB_DIR_LIB_CLASSES', ANALIB_DIR_LIB . DIRECTORY_SEPARATOR . ANALIB_DIR_CLASS_NAME);
define('ANALIB_DIR_LIB_CORE', ANALIB_DIR_LIB . DIRECTORY_SEPARATOR . ANALIB_DIR_CORE_NAME);
define('ANALIB_DIR_LIB_CORE_APPLICATION', ANALIB_DIR_LIB_CORE . DIRECTORY_SEPARATOR . ANALIB_DIR_APPLICATION_NAME);
define('ANALIB_DIR_LIB_CORE_BUILD', ANALIB_DIR_LIB_CORE . DIRECTORY_SEPARATOR . ANALIB_DIR_BUILD_NAME);
define('ANALIB_DIR_LIB_CORE_JPEG', ANALIB_DIR_LIB_CORE . DIRECTORY_SEPARATOR . ANALIB_DIR_JPEG_NAME);
define('ANALIB_DIR_LIB_CORE_DB', ANALIB_DIR_LIB_CORE . DIRECTORY_SEPARATOR . ANALIB_DIR_DB_NAME);
define('ANALIB_DIR_LIB_CORE_DB_MYSQL', ANALIB_DIR_LIB_CORE_DB . DIRECTORY_SEPARATOR . ANALIB_DIR_MYSQL_NAME);
define('ANALIB_DIR_LIB_CORE_FILTERS', ANALIB_DIR_LIB_CORE . DIRECTORY_SEPARATOR . ANALIB_DIR_FILTERS_NAME);
define('ANALIB_DIR_LIB_CORE_FORM', ANALIB_DIR_LIB_CORE . DIRECTORY_SEPARATOR . ANALIB_DIR_FORM_NAME);
define('ANALIB_DIR_LIB_EXCEPTIONS', ANALIB_DIR_LIB_CORE . DIRECTORY_SEPARATOR . ANALIB_DIR_EXCEPTION_NAME);
define('ANALIB_DIR_LIB_HELPER', ANALIB_DIR_LIB . DIRECTORY_SEPARATOR . ANALIB_DIR_HELPER_NAME);
define('ANALIB_DIR_LIB_HELPER_TEMPLATE', ANALIB_DIR_LIB . DIRECTORY_SEPARATOR . ANALIB_DIR_HELPER_TEMPLATE_NAME);
define('ANALIB_DIR_LIB_MODELS', ANALIB_DIR_LIB . DIRECTORY_SEPARATOR . ANALIB_DIR_MODEL_NAME);
define('ANALIB_DIR_LIB_BUSINESS', ANALIB_DIR_LIB . DIRECTORY_SEPARATOR . ANALIB_DIR_BUSINESS_NAME);
define('ANALIB_DIR_LIB_CORE_BUILD_BUSINESS', ANALIB_DIR_LIB_CORE_BUILD . DIRECTORY_SEPARATOR . ANALIB_DIR_BUSINESS_NAME);
define('ANALIB_DIR_LIB_CORE_BUILD_MYSQL', ANALIB_DIR_LIB_CORE_BUILD . DIRECTORY_SEPARATOR . ANALIB_DIR_MYSQL_NAME);
define('ANALIB_DIR_LIB_PROTO', ANALIB_DIR_LIB . DIRECTORY_SEPARATOR . ANALIB_DIR_PROTO_NAME);
define('ANALIB_DIR_LIB_CORE_XML', ANALIB_DIR_LIB_CORE . DIRECTORY_SEPARATOR . ANALIB_DIR_CORE_XML_NAME);
define('ANALIB_DIR_LIB_CORE_FB2', ANALIB_DIR_LIB_CORE . DIRECTORY_SEPARATOR . ANALIB_DIR_CORE_XML_NAME . DIRECTORY_SEPARATOR . ANALIB_DIR_FB2_NAME);
define('ANALIB_DIR_LIB_UTIL', ANALIB_DIR_LIB . DIRECTORY_SEPARATOR . ANALIB_DIR_UTIL_NAME);
define('ANALIB_DIR_LIB_TEMPLATE', ANALIB_DIR_LIB . DIRECTORY_SEPARATOR . ANALIB_DIR_TEMPLATE_NAME);
define('ANALIB_DIR_LIB_VIEWS', ANALIB_DIR_LIB . DIRECTORY_SEPARATOR . ANALIB_DIR_VIEW_NAME);
define('ANALIB_DIR_LIB_XML', ANALIB_DIR_LIB . DIRECTORY_SEPARATOR . ANALIB_DIR_XML);

//	File extensions
define('ANALIB_EXT_CLASS', '.php');
define('ANALIB_EXT_CONTROLLER', ANALIB_EXT_CLASS);
define('ANALIB_EXT_MODEL', ANALIB_EXT_CLASS);
define('ANALIB_EXT_EXCEPTION', ANALIB_EXT_CLASS);
define('ANALIB_EXT_HELPER', ANALIB_EXT_CLASS);
define('ANALIB_EXT_UTIL', ANALIB_EXT_CLASS);
define('ANALIB_EXT_VIEW', '.phtml');
define('ANALIB_EXT_HELPER_VIEW', ANALIB_EXT_VIEW);

//	Class suffix
define('ANALIB_SUF_CONTROLLER', 'Controller');
define('ANALIB_SUF_ACTION', 'Action');
