<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
    <head>
        <title>Domains</title>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <link type="text/css" rel="stylesheet" href="<?= \analib\Core\Application\Application::makeLink('css/style.css') ?>" />
        <link type="text/css" rel="stylesheet" href="<?= \analib\Core\Application\Application::makeLink('css/error.css') ?>" />
    </head>
    <body>
